### ISSUE TITLE
Works perfectly on 1.7.10, but not on 1.7.9

### ISSUE THREAD

**Issue by Tassil0** [NotNV6/PearlThrough#3]
Hi, I want to run this plugin on my 1.7.9R0.2 spigot server, but I get the following error:
```
[22:08:37 ERROR]: Error occurred while enabling Enderpearl v1.9.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/Entity
	at rip.skyland.pearls.PearlPlugin.onEnable(PearlPlugin.java:22) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1483]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [spigot.jar:git-Spigot-1483]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1483]
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:465) [spigot.jar:git-Spigot-1483]
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:383) [spigot.jar:git-Spigot-1483]
	at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:359) [spigot.jar:git-Spigot-1483]
	at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:333) [spigot.jar:git-Spigot-1483]
	at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:289) [spigot.jar:git-Spigot-1483]
	at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:193) [spigot.jar:git-Spigot-1483]
	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:457) [spigot.jar:git-Spigot-1483]
	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1483]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.Entity
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[spigot.jar:git-Spigot-1483]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[spigot.jar:git-Spigot-1483]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
	... 12 more
```
Any idea how this could be fixed? I have little to none experience in Java. I naively tried to compile it with spigot 1.7.9, it compiled fine, but didn't work on the server. Thanks for any help.

**Comment by linsaftw** [comment]
Of course it won't work, this version is coded only for 1.7.10. I will try to fork this plugin and make it multi-version compatible.
